#---
#files:
#	world_filename: "../model/iiwa14/world.urdf"
#	robot_filename: "../model/iiwa14/iiwa14.urdf"
#robot:
#	kp: 100
#	kv: 20
#	q_init: 1.01, -1.02, 1.7, 1.57, -0.35, 1.3, 1.03

---
 world_file: "a deer, a female deer"
 robot_file: "a drop of golden sun"
 pi: 3.14159
 xmas: true
