---
files:
   world_file: "../model/iiwa14/world.urdf"
   robot_file: "../model/iiwa14/iiwa14.urdf"
robot:
   kp: 100
   kv: 20
   q_init: 1.01, -1.02, 1.7, 1.57, -0.35, 1.3, 1.03
# put 3 spaces for each mapping
